function [] = info2table(info, gnit, iter)
% function [] = info2table(info, iter) generates (or updates) a table from
% the armaint debug info.
%
% Inputs:    info - the output structure generated by armaint in debug mode
%            gnit - gap iteration number (useful when armaint is run several 
%               times e.g. inside af_simp)
%
% Optional:  iter - a pair of values [i j] for debugging purposes where i 
%             is used for saving files deb00i.csv and j allow to save 
%             different runs in different folders 00j. Use j=0 for just one
%             folder
%
% Output:   csv files with name benchmark_armax.csv
%
% Version: 0.1
%
% Author(s): Javier Pascual-Granado
% Date: 24/08/2026
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Common info
common = table( ...
    repmat(gnit,3,1), ...
    repmat(info.numel,3,1), ...
    repmat(info.std,3,1), ...
    repmat(info.ordp,3,1), ...
    repmat(info.ordq,3,1), ...
    'VariableNames', { ...
        'Iteration', ...
        'Numel', ...
        'STD', ...
        'p', ...
        'q'});

% Specific info
algrtm = [ ...
    "armax_par"
    "armax"
    "armax_alg"];

ct = [ ...
    info.armax_par_time
    info.armax_time
    info.armax_alg_time];

ok = [ ...
    info.armax_par_ok
    info.armax_ok
    info.armax_alg_ok];

loss = [ ...
    info.armax_par_loss
    info.armax_loss
    info.armax_alg_loss];

specific = table(algrtm, ct, loss, ok, ...
    'VariableNames', {'Algorithm','Comp.Time_s','FitLoss','OK'});

T = [common specific];

% Output folder (optional)
if nargin==3

    afit = iter(1);
    numFolder = iter(2);

    if numFolder==0       % several files but just one folder
        debFolder = 'debFiles';
    elseif numFolder>0    % several files and several folders
        debFolder = sprintf("deb%0.3d", numFolder); % numbered
    end
       
    tablefile = sprintf('%s/benchmark_armax_%d.csv', debFolder, afit);    

    if ~isfolder(debFolder)
        mkdir(debFolder);
    end

else
    tablefile = 'benchmark_armax.csv';
end

% Output file
if ~isfile(tablefile)
    writetable(T, tablefile);
else
    writetable(T, tablefile, ...
    'WriteMode', 'append');
end

% Use:
%  In order to compare computing time from armax_alg and armax_par:
%
% ta = T.Comp_Time_s(T.Algorithm=="armax_alg");
% tp = T.Comp_Time_s(T.Algorithm=="armax_par");
% mask = ta < tp;                      % logical vector
% T_armax_alg = T(T.Algorithm=="armax_alg", :);
% result = T_armax_alg(mask, :);      % rows for armax_alg where ta < tp
